import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion"; // Adjust as needed

const FAQSection = () => {
  return (
    <section id="faq" className="py-12 bg-secondary">
      <div className="container mx-auto max-w-[800px] px-4">
        <h2 className="text-3xl font-bold mb-8 text-center">Frequently Asked Questions</h2>
        <Accordion type="single" collapsible className="w-full">
          <AccordionItem value="item-1">
            <AccordionTrigger className="text-base font-medium leading-loose">
              What is a keyword generator?
            </AccordionTrigger>
            <AccordionContent className="leading-relaxed">
              A keyword generator is a tool that helps you discover relevant search terms and phrases related to your topic or niche. It&apos;s designed to assist in creating effective SEO and content strategies by providing a list of keywords that your target audience is likely to use when searching for information online.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-2">
            <AccordionTrigger className="text-base font-medium leading-loose">
              How does the keyword generator work?
            </AccordionTrigger>
            <AccordionContent className="leading-relaxed">
              Our keyword generator uses advanced algorithms and data from various sources to analyze your input and generate a list of related keywords. It considers factors such as search volume, competition, and relevance to provide you with the most useful keyword suggestions for your content and SEO efforts.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-3">
            <AccordionTrigger className="text-base font-medium leading-loose">
              Can I use the generated keywords for PPC campaigns?
            </AccordionTrigger>
            <AccordionContent className="leading-relaxed">
              Yes, absolutely! The keywords generated by our tool can be used for various purposes, including Pay-Per-Click (PPC) campaigns. They can help you identify potential ad keywords, improve your ad targeting, and optimize your campaign structure for better performance and ROI.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-4">
            <AccordionTrigger className="text-base font-medium leading-loose">
              How often is the keyword data updated?
            </AccordionTrigger>
            <AccordionContent className="leading-relaxed">
              We update our keyword data regularly to ensure you have access to the most current and relevant information. Our system refreshes the data weekly, incorporating the latest search trends and algorithm changes from major search engines.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-5">
            <AccordionTrigger className="text-base font-medium leading-loose">
              Is there a limit to how many keywords I can generate?
            </AccordionTrigger>
            <AccordionContent className="leading-relaxed">
              The number of keywords you can generate depends on your subscription plan. Our free plan allows for a limited number of keyword generations per day, while our premium plans offer higher or unlimited generation capabilities. Check our pricing page for more details on the limits for each plan.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </section>
  );
};

export default FAQSection;
